import pandas as pd
import pytest

from data_inclusion.tasks.sources import odspep


@pytest.fixture
def odspep_sample_df():
    return pd.DataFrame(
        [
            {
                "ID_RES": "48368",
                "LIBELLE_SERVICE": None,
                "REGION_SERVICE": None,
                "REGION SERVICE LIBELLE": None,
                "DEPT_SERVICE": None,
                "Departement Service": None,
                "COM_SERVICE": "60175",
                "DATE_DEBUT_SERVIC": "03/07/18",
                "DATE_FIN_SERVICE": "03/07/28",
                "DESCRIPTION_SERVICE": "Accueil offre de service\n- Petite enfance\n- enfance et jeunesse\n- solidarité et insertion\n- logement et cadre de vie",
                "PERIMETRE_GEO": "5",
                "STRUCTURE": "CAF DE CREIL",
                "SERVICE_RSP": "Accueil Droits et Prestations - Droits et Informations sur aides",
                "MODALITE_ACCES_RSP": "1",
                "ModaliteAcces": "Accès libre",
                "CODE_FAM": "1",
                "FamilleBesoin": "Contraintes personnelles",
                "CODE_CAT": "4",
                "Besoin": "Faire face à des difficultés financières",
                "CODE_SSC": "16",
                "Sous besoin": "Bénéficier d'aides financières (hors celles de Pôle Emploi)",
                "ID_ADR": "24247",
                "L1_IDENTIFICATION_DEST_ADR": "CAF DE CREIL",
                "L2_IDENTITE_DEST_ADR": None,
                "L4_NUMERO_LIB_VOIE_ADR": "2 Rue Charles-Auguste Duguet",
                "L3_COMPLEMENT_ADR": None,
                "L5_MENTION_ADR": None,
                "L7_PAYS_ADR": "FRANCE",
                "LATITUDE_ADR": "49.260956",
                "LONGITUDE_ADR": "2.47524",
                "EST_NORMALISEE_ADR": "1",
                "CODE_COMMUNE_ADR": "60175",
                "CODE_POSTAL_ADR": "60100",
                "LIBELLE_COMMUNE_ADR": " Creil",
                "ID_CTC": "23056",
                "TEL_1_CTC": "0810256080",
                "TEL_2_CTC": None,
                "FAX_CTC": None,
                "SITE_INTERNET_CTC": None,
                "MAIL_CTC": "www@caf.fr",
                "CODE_TAG_TPU": None,
                "VALEUR_TAG_TPU": None,
                "Critere type Public - Niveau de formation": None,
                "Critere type Public": None,
                "JOUR_HOR": None,
                "HD_AM_HOR": None,
                "HF_AM_HOR": None,
                "HD_PM_HOR": None,
                "HF_PM_HOR": None,
                "COMMENTAIRES_HORAIRE_RSP": "lundi au vendredi 8h30/16h30",
                "TYPE_RES_PART_RSP": "0",
                "type service partenaire ": "Ressource Sociale",
                "DATE DERNIERE MAJ": "00:00:00",
            },
            {
                "ID_RES": "48368",
                "LIBELLE_SERVICE": None,
                "REGION_SERVICE": None,
                "REGION SERVICE LIBELLE": None,
                "DEPT_SERVICE": None,
                "Departement Service": None,
                "COM_SERVICE": "60175",
                "DATE_DEBUT_SERVIC": "03/07/18",
                "DATE_FIN_SERVICE": "03/07/28",
                "DESCRIPTION_SERVICE": "Accueil offre de service\n- Petite enfance\n- enfance et jeunesse\n- solidarité et insertion\n- logement et cadre de vie",
                "PERIMETRE_GEO": "5",
                "STRUCTURE": "CAF DE CREIL",
                "SERVICE_RSP": "Accueil Droits et Prestations - Droits et Informations sur aides",
                "MODALITE_ACCES_RSP": "1",
                "ModaliteAcces": "Accès libre",
                "CODE_FAM": "1",
                "FamilleBesoin": "Contraintes personnelles",
                "CODE_CAT": "7",
                "Besoin": "Faire face à des difficultés administratives ou juridiques",
                "CODE_SSC": "23",
                "Sous besoin": "Régler un problème administratif ou juridique",
                "ID_ADR": "24247",
                "L1_IDENTIFICATION_DEST_ADR": "CAF DE CREIL",
                "L2_IDENTITE_DEST_ADR": None,
                "L4_NUMERO_LIB_VOIE_ADR": "2 Rue Charles-Auguste Duguet",
                "L3_COMPLEMENT_ADR": None,
                "L5_MENTION_ADR": None,
                "L7_PAYS_ADR": "FRANCE",
                "LATITUDE_ADR": "49.260956",
                "LONGITUDE_ADR": "2.47524",
                "EST_NORMALISEE_ADR": "1",
                "CODE_COMMUNE_ADR": "60175",
                "CODE_POSTAL_ADR": "60100",
                "LIBELLE_COMMUNE_ADR": " Creil",
                "ID_CTC": "23056",
                "TEL_1_CTC": "0810256080",
                "TEL_2_CTC": None,
                "FAX_CTC": None,
                "SITE_INTERNET_CTC": None,
                "MAIL_CTC": "www@caf.fr",
                "CODE_TAG_TPU": None,
                "VALEUR_TAG_TPU": None,
                "Critere type Public - Niveau de formation": None,
                "Critere type Public": None,
                "JOUR_HOR": None,
                "HD_AM_HOR": None,
                "HF_AM_HOR": None,
                "HD_PM_HOR": None,
                "HF_PM_HOR": None,
                "COMMENTAIRES_HORAIRE_RSP": "lundi au vendredi 8h30/16h30",
                "TYPE_RES_PART_RSP": "0",
                "type service partenaire ": "Ressource Sociale",
                "DATE DERNIERE MAJ": "00:00:00",
            },
        ]
    )


def test_transform_odspep(odspep_sample_df):
    df = odspep.transform_dataframe(odspep_sample_df)

    assert df.to_dict(orient="records") == [
        {
            "id": "48368",
            "siret": None,
            "rna": None,
            "nom": "CAF DE CREIL",
            "commune": " Creil",
            "code_postal": "60100",
            "code_insee": "60175",
            "adresse": "2 Rue Charles-Auguste Duguet",
            "complement_adresse": None,
            "longitude": "2.47524",
            "latitude": "49.260956",
            "typologie": "CAF",
            "telephone": "0810256080",
            "courriel": "www@caf.fr",
            "site_web": None,
            "presentation_resume": None,
            "presentation_detail": None,
            "source": "odspep",
            "date_maj": "00:00:00",
            "structure_parente": None,
            "lien_source": None,
            "horaires_ouverture": None,
            "accessibilite": None,
            "labels_nationaux": None,
            "labels_autres": None,
        }
    ]
