name: staging

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  process:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Installation des scripts
        run: |
          pip install -U pip setuptools wheel
          pip install -e .
      - name: Import dora vers staging
        env:
          DI_API_URL: ${{ secrets.DI_API_STAGING_URL }}
        run: |
          data-inclusion import --src-type dora https://api.dora.fabrique.social.gouv.fr/api/v1/structures/
      - name: Import itou vers staging
        env:
          DI_API_URL: ${{ secrets.DI_API_STAGING_URL }}
          ITOU_API_TOKEN: ${{ secrets.ITOU_API_TOKEN }}
        run: |
          data-inclusion import --src-type itou https://emplois.inclusion.beta.gouv.fr/api/v1/structures/
